import type { Task } from '../../api/client';

export const sampleTasks: Task[] = [
  {
    id: 1,
    title: 'Set up project structure',
    description: 'Scaffold the pnpm workspace and initial tooling.',
    status: 'to-start',
    location: 'Home office',
    urgency: 2,
    dueDate: '2026-09-08T09:00:00.000Z',
    parentTaskId: null,
    recurrence: null,
    tags: ['setup'],
    assignees: [{ id: 1, name: 'Alex' }],
    comments: [],
    createdAt: '2026-09-01T08:00:00.000Z',
    updatedAt: '2026-09-01T08:00:00.000Z',
  },
  {
    id: 2,
    title: 'Write backend REST endpoints',
    description: 'Task CRUD with status transitions and tag assignment.',
    status: 'started',
    location: null,
    urgency: 3,
    dueDate: '2026-09-10T09:00:00.000Z',
    parentTaskId: null,
    recurrence: null,
    tags: ['backend'],
    assignees: [{ id: 2, name: 'Sam' }],
    comments: [],
    createdAt: '2026-09-02T08:00:00.000Z',
    updatedAt: '2026-09-03T10:30:00.000Z',
  },
  {
    id: 3,
    title: 'Implement MCP tools',
    description: 'Expose the task tools over the MCP server.',
    status: 'in-progress',
    location: 'Desk',
    urgency: 5,
    dueDate: '2026-09-12T09:00:00.000Z',
    parentTaskId: null,
    recurrence: null,
    tags: ['mcp', 'backend'],
    assignees: [
      { id: 1, name: 'Alex' },
      { id: 3, name: 'Riley' },
    ],
    comments: [
      {
        id: 1,
        body: 'Sessions need invalidation on restart.',
        status: 'in-progress',
        createdAt: '2026-09-04T09:00:00.000Z',
      },
    ],
    createdAt: '2026-09-03T08:00:00.000Z',
    updatedAt: '2026-09-04T09:00:00.000Z',
  },
  {
    id: 4,
    title: 'Integrate Storybook',
    description: 'Set up the component workbench with Tailwind v4.',
    status: 'on-hold',
    location: null,
    urgency: null,
    dueDate: null,
    parentTaskId: null,
    recurrence: null,
    tags: ['frontend'],
    assignees: [{ id: 2, name: 'Sam' }],
    comments: [
      {
        id: 2,
        body: 'Waiting on the design token decision.',
        status: 'on-hold',
        createdAt: '2026-09-05T09:00:00.000Z',
      },
    ],
    createdAt: '2026-09-04T08:00:00.000Z',
    updatedAt: '2026-09-05T09:00:00.000Z',
  },
  {
    id: 5,
    title: 'Review pull requests',
    description: 'Sanity-check the transport swap before merging.',
    status: 'validating',
    location: 'Coffee shop',
    urgency: 4,
    dueDate: '2026-09-13T09:00:00.000Z',
    parentTaskId: null,
    recurrence: null,
    tags: ['review'],
    assignees: [{ id: 3, name: 'Riley' }],
    comments: [
      {
        id: 3,
        body: 'Looks good, one naming nit.',
        status: 'validating',
        createdAt: '2026-09-06T09:00:00.000Z',
      },
    ],
    createdAt: '2026-09-05T08:00:00.000Z',
    updatedAt: '2026-09-06T09:00:00.000Z',
  },
  {
    id: 6,
    title: 'Write release notes',
    description: 'Summarize the v1.0.0 changes for the team.',
    status: 'finished',
    location: null,
    urgency: 1,
    dueDate: '2026-09-01T09:00:00.000Z',
    parentTaskId: null,
    recurrence: null,
    tags: ['docs'],
    assignees: [],
    comments: [],
    createdAt: '2026-08-30T08:00:00.000Z',
    updatedAt: '2026-09-01T09:00:00.000Z',
  },
  {
    id: 7,
    title: 'Refactor the entire task scheduling engine to support long-running background workers',
    description:
      'This is a deliberately long description used to verify the line-clamp ellipsis behavior in the deck cards. It rambles on about the scheduling engine, worker pools, backpressure handling, retry policies with exponential backoff, circuit breakers, and the observability instrumentation that must be added so that we can trace every job from enqueue to completion without losing any state across process restarts. The text keeps going past two lines so the deck card has to truncate it with an ellipsis instead of growing beyond the uniform card height.',
    status: 'in-progress',
    location: 'Engineering lab',
    urgency: 5,
    dueDate: '2026-09-20T09:00:00.000Z',
    parentTaskId: null,
    recurrence: null,
    tags: ['backend', 'scheduling', 'observability'],
    assignees: [
      { id: 1, name: 'Alex' },
      { id: 2, name: 'Sam' },
    ],
    comments: [],
    createdAt: '2026-09-05T08:00:00.000Z',
    updatedAt: '2026-09-06T09:00:00.000Z',
  },
];
